First implementation for private timeline
harames2001/Sniffable pull request #36
Opened 2021-05-14 17:00 UTC by michael1929

WARNING: Needs a new Database file

2021-05-14 20:48 UTC, Thomas131 requested changes
See comments (not sure if needed). Looks good to me otherwise. Thanks for that!

2021-05-14 20:48 UTC, Thomas131 commented on src/main/java/at/ac/fhstp/Sniffable/datamodel/Comment.java
Is there a @Column or something missing?

2021-05-14 20:48 UTC, Thomas131 commented on src/main/java/at/ac/fhstp/Sniffable/datamodel/Comment.java
Ups, I didn't want to mention a user, sorry @Column

2021-05-14 20:48 UTC, Thomas131 commented on src/main/java/at/ac/fhstp/Sniffable/datamodel/Pupdate.java
> +    private long timestamp;
same

2021-05-15 15:53 UTC, Thomas131 approved these changes

2021-05-16 09:24 UTC, harames2001 approved these changes
well done

2021-05-16 09:25 UTC, merged